function f = f_gen(in1)
%F_GEN
%    F = F_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-May-2019 19:53:37

theta = in1(4,:);
vel = in1(3,:);
f = [vel.*cos(theta);vel.*sin(theta);0.0;0.0];
