function Lfh = Lfh_gen(in1)
%LFH_GEN
%    LFH = LFH_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-May-2019 19:53:37

theta = in1(4,:);
vel = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(theta);
t3 = x.^2;
t4 = y.^2;
t5 = t3+t4+1.0e-5;
t6 = 1.0./sqrt(t5);
t7 = sin(theta);
t8 = 1.0./t5.^(3.0./2.0);
t9 = t2.*t6.*vel.*x;
t10 = t6.*t7.*vel.*y;
t11 = t9+t10;
Lfh = -t2.*vel.*(t6.*x-t11.*(-t2.*t6.*vel+t2.*t3.*t8.*vel+t7.*t8.*vel.*x.*y))-t7.*vel.*(t6.*y-t11.*(-t6.*t7.*vel+t4.*t7.*t8.*vel+t2.*t8.*vel.*x.*y));
