function Lgh2 = Lgh2_gen(in1,in2)
%LGH2_GEN
%    LGH2 = LGH2_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-May-2019 19:53:38

u1 = in2(1,:);
vel = in1(3,:);
Lgh2 = u1.*vel.*2.0;
